In [1]:
import pandas as pd
import numpy as np

In [3]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [4]:
array_1d

array([1, 2, 3, 4, 5])

In [5]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# Sum
sum_1d = np.sum(array_1d)
sum_2d = np.sum(array_2d)

# Mean
mean_1d = np.mean(array_1d)
mean_2d = np.mean(array_2d)

# Max
max_1d = np.max(array_1d)
max_2d = np.max(array_2d)

# Reshape
reshaped_array = np.reshape(array_1d, (5, 1))  # from (5,) to (5,1)


In [7]:
sum_1d

np.int64(15)

In [8]:
sum_2d

np.int64(21)

In [9]:
mean_1d

np.float64(3.0)

In [10]:
mean_2d

np.float64(3.5)

In [11]:
max_1d

np.int64(5)

In [12]:
max_2d

np.int64(6)

In [13]:
reshaped_array

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
print("1D Array:", array_1d)
print("2D Array:\n", array_2d)
print("Sum of 1D Array:", sum_1d)
print("Mean of 2D Array:", mean_2d)
print("Max of 1D Array:", max_1d)
print("Reshaped Array:\n", reshaped_array)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Sum of 1D Array: 15
Mean of 2D Array: 3.5
Max of 1D Array: 5
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [17]:
# Load CSV File

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')

In [3]:
# Display the First 10 Rows

In [4]:
print(df.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54

In [31]:
# Display Column Names

In [32]:
print("Column names:", df.columns.tolist())

Column names: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [33]:
# Check for Null Values

In [34]:
print("Null values per column:\n", df.isnull().sum())

Null values per column:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [35]:
# Filter Rows Where Age > 30

In [36]:
filtered_df = df[df['Age'] > 30]

In [38]:
filtered_df.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
4             5         0       3   
6             7         0       1   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
4       0    373450   8.0500   NaN        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S

In [5]:
import pandas as pd

# Load Titanic dataset
df = pd.read_csv('Titanic-Dataset.csv')  

# Select numerical columns for analysis
numerical_columns = df.select_dtypes(include='number')

# Initialize an empty dictionary to store the results
stats = {}

# Compute statistics for each numerical column
for column in numerical_columns.columns:
    stats[column] = {
        'mean': numerical_columns[column].mean(),
        'median': numerical_columns[column].median(),
        'mode': numerical_columns[column].mode().tolist(),  # Mode can return multiple values
        'min': numerical_columns[column].min(),
        'max': numerical_columns[column].max()
    }

# Convert to a DataFrame for better readability
stats_df = pd.DataFrame(stats).T  # Transpose for cleaner layout

# Display the result
print(stats_df)


                  mean   median  \
PassengerId      446.0    446.0   
Survived      0.383838      0.0   
Pclass        2.308642      3.0   
Age          29.699118     28.0   
SibSp         0.523008      0.0   
Parch         0.381594      0.0   
Fare         32.204208  14.4542   

                                                          mode   min       max  
PassengerId  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...     1       891  
Survived                                                   [0]     0         1  
Pclass                                                     [3]     1         3  
Age                                                     [24.0]  0.42      80.0  
SibSp                                                      [0]     0         8  
Parch                                                      [0]     0         6  
Fare                                                    [8.05]   0.0  512.3292  


In [12]:
import pandas as pd

# Load the Titanic dataset
df = pd.read_csv('Titanic-Dataset.csv')

# -------------------------
# 1. Fill missing numeric values with the mean
# -------------------------
df_filled_mean = df.copy()
numeric_cols = df_filled_mean.select_dtypes(include='number').columns

for col in numeric_cols:
    if df_filled_mean[col].isnull().sum() > 0:
        df_filled_mean[col].fillna(df_filled_mean[col].mean(), inplace=True)

# -------------------------
# 2. Remove rows with any null values
# -------------------------
df_no_nulls = df.dropna()

# -------------------------
# 3. Drop columns with any null values
# -------------------------
df_drop_cols = df.dropna(axis=1)

# -------------------------
# Show which columns had nulls
# -------------------------
null_counts = df.isnull().sum()
print("Columns with missing values:\n", null_counts[null_counts > 0])



Columns with missing values:
 Age         177
Cabin       687
Embarked      2
dtype: int64


C:\Users\Home\AppData\Local\Temp\ipykernel_1524\3379891083.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filled_mean[col].fillna(df_filled_mean[col].mean(), inplace=True)
